version: '3'                                                           
services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    networks:
      - cdc-setup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker
    ports:
      - "80:80"
    networks:
      - cdc-setup
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres

  jenkins:
    image: cdc-expert-talk/jenkins-cdc
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
    networks:
      - cdc-setup
    environment:
      - JAVA_OPTS=-Xmx2G

  nexus-data:
    image: sonatype/nexus
    volumes:
      - "nexus-repo"
    networks:
      - cdc-setup

  mynexus:
    image: sonatype/nexus
    ports:
      - "8081:8081"
    volumes:
      - "nexus-repo"
    networks:
      - cdc-setup

volumes:
  jenkins_home:
  nexus-repo:  

networks:
  cdc-setup:
